### ISSUE TITLE
Server no longer responds regularly

### ISSUE THREAD

**Issue by KleinDevDE** [JorelAli/1.13-Command-API#42] opened 2019-01-12 15:05 UTC
**Describe the bug**
Server no longer responds regularly

**Expected behavior**
We don't know, he just crashes or stop responding sometime then.
Without anyone executing a command

**Additional infos**
https://pastebin.com/MVx425Hk

**Currently we are starting a trial without CommandAPI**

**Comment by JorelAli** [comment] 2019-01-12 15:15
What version of CommandAPI are you using?

**Comment by KleinDevDE** [comment] 2019-01-12 18:15
Previously CommandAPI 1.5 with Paperclip 406

Now CommandAPI 1.8.2 with Paperclip 456

Tested versions
CommandAPI 1.8.2 & Paperclip 498 -- stop responding
CommandAPI 1.8.2 & Paperclip 456 -- stop responding
CommandAPI 1.5 & Paperclip 456 -- Could not load
CommandAPI 1.8.1 & Paperclip 456 -- stop responding
CommandAPI 1.8.1 & Paperclip 498 -- stop responding


The test without the plugin ran without problems so far.

**Comment by KleinDevDE** [comment] 2019-01-13 10:57
While the test server was running with the CommandAPI, it finally crashed because of too little memory. There are mentions of the CommandAPI in the thread dump, I don't know if it helps.

https://pastebin.com/91uHMnGe

**Comment by JorelAli** [comment] 2019-01-13 15:46
Thanks for that, I believe that'll be a lot of help to help me find the root of the issue.
I'll take a look into it at a later date (~ a week or so), I've currently got some massive deadline in a few days.

**Comment by KleinDevDE** [comment] 2019-02-03 00:13
Found something?

**Comment by JorelAli** [comment] 2019-02-03 02:55
@KleinDevDE I wish I could say I've made progress, but to be honest, I've not had the time to get started.

**Comment by KleinDevDE** [comment] 2019-02-09 10:31
I'm currently running the server with the plugin, let's see what happens in the next hours

**Comment by KleinDevDE** [comment] 2019-02-09 13:18
[14:08:51] [Paper Watchdog Thread/ERROR]: --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH  - git-Paper-456 (MC: 1.13.2) ---
[14:08:51] [Paper Watchdog Thread/ERROR]: The server has not responded for 58 seconds! Creating thread dump
[14:08:51] [Paper Watchdog Thread/ERROR]: ------------------------------
[14:08:51] [Paper Watchdog Thread/ERROR]: Server thread dump (Look for plugins here before reporting to Paper!):
[14:08:51] [Paper Watchdog Thread/ERROR]: ------------------------------
[14:08:51] [Paper Watchdog Thread/ERROR]: Current Thread: Server thread
[14:08:51] [Paper Watchdog Thread/ERROR]:       PID: 26 | Suspended: false | Native: false | State: RUNNABLE
[14:08:51] [Paper Watchdog Thread/ERROR]:       Stack:
[14:08:51] [Paper Watchdog Thread/ERROR]:               java.lang.Class.forName0(Native Method)
[14:08:51] [Paper Watchdog Thread/ERROR]:               java.lang.Class.forName(Class.java:264)
[14:08:51] [Paper Watchdog Thread/ERROR]:               io.github.jorelali.commandapi.api.SemiReflector.getNMSClass(SemiReflector.java:829)
[14:08:51] [Paper Watchdog Thread/ERROR]:               io.github.jorelali.commandapi.api.SemiReflector.lambda$generateCommand$1(SemiReflector.java:200)
[14:08:51] [Paper Watchdog Thread/ERROR]:               io.github.jorelali.commandapi.api.SemiReflector$$Lambda$2079/174187490.run(Unknown Source)
[14:08:51] [Paper Watchdog Thread/ERROR]:               com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:132)
[14:08:51] [Paper Watchdog Thread/ERROR]:               com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:72)
[14:08:51] [Paper Watchdog Thread/ERROR]:               net.minecraft.server.v1_13_R2.CommandDispatcher.a(CommandDispatcher.java:188)
[14:08:51] [Paper Watchdog Thread/ERROR]:               net.minecraft.server.v1_13_R2.CommandDispatcher.a(CommandDispatcher.java:169)
[14:08:51] [Paper Watchdog Thread/ERROR]:               net.minecraft.server.v1_13_R2.CommandDispatcher.dispatchServerCommand(CommandDispatcher.java:165)
[14:08:51] [Paper Watchdog Thread/ERROR]:               net.minecraft.server.v1_13_R2.CommandBlockListenerAbstract.a(CommandBlockListenerAbstract.java:111)
[14:08:51] [Paper Watchdog Thread/ERROR]:               net.minecraft.server.v1_13_R2.BlockCommand.a(BlockCommand.java:95)
[14:08:51] [Paper Watchdog Thread/ERROR]:               net.minecraft.server.v1_13_R2.BlockCommand.a(BlockCommand.java:71)
[14:08:51] [Paper Watchdog Thread/ERROR]:               net.minecraft.server.v1_13_R2.IBlockData.a(IBlockData.java:215)
[14:08:51] [Paper Watchdog Thread/ERROR]:               net.minecraft.server.v1_13_R2.WorldServer.b(WorldServer.java:691)
[14:08:51] [Paper Watchdog Thread/ERROR]:               net.minecraft.server.v1_13_R2.WorldServer$$Lambda$1924/814898367.accept(Unknown Source)
[14:08:51] [Paper Watchdog Thread/ERROR]:               net.minecraft.server.v1_13_R2.TickListServer.a(TickListServer.java:85)
[14:08:51] [Paper Watchdog Thread/ERROR]:               net.minecraft.server.v1_13_R2.WorldServer.q(WorldServer.java:672)
[14:08:51] [Paper Watchdog Thread/ERROR]:               net.minecraft.server.v1_13_R2.WorldServer.doTick(WorldServer.java:313)
[14:08:51] [Paper Watchdog Thread/ERROR]:               net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1088)
[14:08:51] [Paper Watchdog Thread/ERROR]:               net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439)
[14:08:51] [Paper Watchdog Thread/ERROR]:               net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:943)
[14:08:51] [Paper Watchdog Thread/ERROR]:               net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:841)
[14:08:51] [Paper Watchdog Thread/ERROR]:               java.lang.Thread.run(Thread.java:748)
[14:08:51] [Paper Watchdog Thread/ERROR]: ------------------------------
[14:08:51] [Paper Watchdog Thread/ERROR]: --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH ---
[14:08:51] [Paper Watchdog Thread/ERROR]: ------------------------------

**Comment by KleinDevDE** [comment] 2019-02-15 15:10
Still waiting :thinking: :smile:

**Comment by JorelAli** [comment] 2019-02-15 15:32
> Still waiting 🤔 😄

And I'm still busy at university 🙁. Exam day today. Hopefully, I'll be able to get time to look over it next week!

**Comment by KleinDevDE** [comment] 2019-02-17 01:49
Here is the full log: https://cloud.kleindev.de/s/XT9sirg5Jnf7znc
(The full log is too long for pastebin, so I have uploaded it to my cloud)

**Comment by JorelAli** [comment] 2019-02-17 11:54
You appear to be running version 1.8.2. In order to find the source code for that, you must make sure you're looking at the 1.8.2 tag. Therefore, the two lines we're looking for are [SemiReflector.java line 200](https://github.com/JorelAli/1.13-Command-API/blob/8bac91c59e2bc8a4786055fa1429d2f540a5f207/1.13CommandAPI/src/io/github/jorelali/commandapi/api/SemiReflector.java#L200) and [SemiReflector.java line 892](https://github.com/JorelAli/1.13-Command-API/blob/8bac91c59e2bc8a4786055fa1429d2f540a5f207/1.13CommandAPI/src/io/github/jorelali/commandapi/api/SemiReflector.java#L892). 

However, I believe the issue may arise inside the lambda, as stated in your logs:
```
io.github.jorelali.commandapi.api.SemiReflector.getNMSClass(SemiReflector.java:829)
io.github.jorelali.commandapi.api.SemiReflector.lambda$generateCommand$1(SemiReflector.java:200)
io.github.jorelali.commandapi.api.SemiReflector$$Lambda$2079/174187490.run(Unknown Source)
```

```
io.github.jorelali.commandapi.api.SemiReflector.getMethod(SemiReflector.java:848)
io.github.jorelali.commandapi.api.SemiReflector.lambda$generateCommand$1(SemiReflector.java:200)
io.github.jorelali.commandapi.api.SemiReflector$$Lambda$2079/174187490.run(Unknown Source)
```

```
io.github.jorelali.commandapi.api.SemiReflector.getMethod(SemiReflector.java:844)
io.github.jorelali.commandapi.api.SemiReflector.getCommandSender(SemiReflector.java:709)
io.github.jorelali.commandapi.api.SemiReflector.lambda$generatePermissions$2(SemiReflector.java:530)
io.github.jorelali.commandapi.api.SemiReflector$$Lambda$2080/1331786205.test(Unknown Source)
```

All of these stack traces lead to some lambda from an "unknown source" and lead to various different lambdas, which I believe correlates to **the code which is implemented by you**. Does the CommandAPI produce any issues when it is loaded with no commands? _(i.e. if you load the CommandAPI onto Paper with nothing actually using it, does it produce issues?)_

**Comment by JorelAli** [comment] 2019-02-23 08:42
After some exploration, I believe that I could look at implementing a parsing cache system, however it's quite unreliable to achieve such a setup. It involves using the CommandPreProcessEvent to manually handle specific commands, and the amount of reflection required to achieve this parsing may not actually be worth the time. _(i.e. time to check and cache parsing and pass it to the vanilla command dispatcher by using reflection may be more costly than letting vanilla parse the command each time)_

You can read more about how it's possible to cache commands here: https://github.com/Mojang/brigadier#parsing-user-input

I've found a group of people that are working with me to resolve the issue, but cannot make any guarantee that we'll find a solution.

**Comment by KleinDevDE** [comment] 2019-02-23 15:34
Thank you for your efforts so far to fix this problem!

Our server uses hundreds of command blocks, like the implementation of a shop, own minigames or small things like teleport, weather change etc.

```I don't really like the idea of the CommandAPI using the `CommandPreProcessEvent`, because I believe other players should be able to modify that event themselves.```
You could offer an option in the config which variant should be used.
In the code itself you could then check the set value within the onEnable and call/register the respective listeners/class/methods depending on the assignment.

It would be great if this would be possible and also lead to the solution of the problem :)

**Comment by JorelAli** [comment] 2019-04-30 00:34
I've decided to close this issue for now for the following reasons:

- I don't use paperspigot as my primary testing environment
- I've been unable to reproduce the bug at hand
- Due to the upcoming release for compatibility with Minecraft 1.14 (#45), major adjustments were made to heavily improve performance _(Removed a lot of reflective calls and other general performance improvements)_

If this issue arises after the released version of the CommandAPI (Look out for version 2.0!), feel free to re-open, or preferably, create a new issue outlining the problem.

Thanks for your time and sorry for any inconvenience this has caused.

🙇

**Closed by JorelAli** 2019-04-30 00:34 UTC
