### ISSUE TITLE
Aliases on a command with no arguments fail to execute

### ISSUE THREAD

**Issue by i509VCB** [JorelAli/1.13-Command-API#49] opened 2019-05-22 02:16 UTC
**CommandAPI version**
2.0

**Describe the bug**
When registering a command with no arguments, aliases do not work when there are 0 arguments.

**My code**
This code reproduces the behavior:
```java
 LinkedHashMap<String, Argument> arguments = new LinkedHashMap<String, Argument>();
        
        String[] aliases = {"portaltrap", "portal", "pe"};
        CommandAPI.getInstance().register("portalescape", CommandPermission.NONE, aliases , arguments, (sender, args)->{
            sender.sendMessage("Message Describing Plugin");
        });
```

**Expected behavior**
Command should execute when using aliases when no arguments are specified.

**Additional context**
This command only sends a message to the sender about the plugin.

The aliases work fine when there is at least one argument.

**Comment by JorelAli** [comment] 2019-05-22 02:31
https://jorelali.github.io/1.13-Command-API/aliases.html#the-alias-bug

Duplicate of #43

**Closed by JorelAli** 2019-05-22 02:31 UTC
Labels: Duplicate
